version: '3.8'

services:
  db:
    image: couchdb:3 # Use official CouchDB image version 3.x
    container_name: i2b_couchdb
    restart: unless-stopped
    environment:
      # These variables will be picked up from the .env file by default
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
      - couchdb_data:/opt/couchdb/data # Persist database data
    ports:
      - "5984:5984" # Expose CouchDB port to the host
    healthcheck:
      # Basic check: See if CouchDB responds to a request on its port
      test: ["CMD", "curl", "-f", "http://localhost:5984/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s # Give CouchDB time to initialize

  app:
    container_name: i2b_app
    build: . # Build the image from the Dockerfile in the current directory
    restart: unless-stopped
    env_file:
      - .env # Load environment variables from .env file
    environment:
      # Override COUCHDB_URL to point to the db service within the Docker network
      - COUCHDB_URL=http://db:5984/
    ports:
      - "8000:8000" # Map host port 8000 to container port 8000
    depends_on:
      db:
        condition: service_healthy # Wait for the db service to be healthy

volumes:
  couchdb_data: # Define the named volume for data persistence
    driver: local
